# Site settings
title: lauris.github.io
email: lauris@discuss.lv
description: "A fucking awesome blog about programming, hacking, open-source, startups, git, vim, linux, etc."
baseurl: ""
url: "http://lauris.github.io"
twitter_username: lauriswat
github_username:  lauris

# Build settings
markdown: kramdown
permalink: none
